create table empresa (id_empresa int(10) not null auto_increment, nb_nombre varchar(255) not null unique, tx_rfc varchar(13), primary key (id_empresa));
create table usuario (id_usuario int(10) not null auto_increment, tx_login varchar(30) not null unique, tx_password varchar(256) not null, tx_nombre varchar(50) not null, tx_primer_ap varchar(50) not null, tx_segundo_ap varchar(50) not null, primary key (id_usuario));
create table empresa_usuario (id_empresa int(10) not null, id_usuario int(10) not null, primary key (id_empresa, id_usuario));
create table diagrama (id_diagrama int(10) not null auto_increment, id_empresa int(10) not null, id_usuario int(10) not null, nb_diagrama varchar(100) not null, tx_path varchar(100) not null unique, primary key (id_diagrama));
create table relacion (id_relacion int(10) not null auto_increment, id_diagrama int(10) not null, id_tipo int(10) not null, id_origen int(10) not null, id_destino int(10) not null, primary key (id_relacion));
create table clase (id_clase int(10) not null, id_diagrama int(10) not null, primary key (id_clase));
create table tipo_relacion (id_tipo int(10) not null auto_increment, nb_tipo varchar(50) not null unique, primary key (id_tipo));
create table atributo (id_clase int(10) not null, id_atributo int(10) not null, id_acceso int(10) not null, id_alcance int(10), id_tipo_dato int(10) not null, nb_atributo int(10) not null, tx_valor varchar(100), primary key (id_clase, id_atributo));
create table metodo (id_clase int(10) not null, id_metodo int(10) not null, id_acceso int(10) not null, id_alcance int(10), id_tipo int(10) not null, nb_metodo int(10) not null, primary key (id_clase, id_metodo));
create table acceso (id_tipo int(10) not null auto_increment, nb_tipo varchar(20) not null unique, primary key (id_tipo));
create table alcance (id_alcance int(10) not null auto_increment, nb_alcance int(10) not null, primary key (id_alcance));
create table tipo_dato (id_tipo int(10) not null auto_increment, nb_tipo int(10), st_primitivo tinyint(1), primary key (id_tipo));
create table parametro (id_clase int(10) not null, id_metodo int(10) not null, id_parametro int(10) not null, id_tipo_dato int(10) not null, nb_parametro int(10), primary key (id_clase, id_metodo, id_parametro));
create table excepcion (id_clase int(10) not null, id_metodo int(10) not null, id_excepcion int(11) not null, id_tipo int(10) not null, primary key (id_clase, id_metodo, id_excepcion));
alter table empresa_usuario add index FKempresa_us18985 (id_empresa), add constraint FKempresa_us18985 foreign key (id_empresa) references empresa (id_empresa);
alter table empresa_usuario add index FKempresa_us820295 (id_usuario), add constraint FKempresa_us820295 foreign key (id_usuario) references usuario (id_usuario);
alter table diagrama add index FKdiagrama496605 (id_empresa, id_usuario), add constraint FKdiagrama496605 foreign key (id_empresa, id_usuario) references empresa_usuario (id_empresa, id_usuario);
alter table relacion add index FKrelacion182327 (id_tipo), add constraint FKrelacion182327 foreign key (id_tipo) references tipo_relacion (id_tipo);
alter table atributo add index FKatributo567857 (id_acceso), add constraint FKatributo567857 foreign key (id_acceso) references acceso (id_tipo);
alter table metodo add index FKmetodo2461 (id_acceso), add constraint FKmetodo2461 foreign key (id_acceso) references acceso (id_tipo);
alter table atributo add index FKatributo712716 (id_alcance), add constraint FKatributo712716 foreign key (id_alcance) references alcance (id_alcance);
alter table metodo add index FKmetodo857601 (id_alcance), add constraint FKmetodo857601 foreign key (id_alcance) references alcance (id_alcance);
alter table clase add index FKclase9966 (id_diagrama), add constraint FKclase9966 foreign key (id_diagrama) references diagrama (id_diagrama);
alter table atributo add index FKatributo943914 (id_tipo_dato), add constraint FKatributo943914 foreign key (id_tipo_dato) references tipo_dato (id_tipo);
alter table metodo add index FKmetodo98695 (id_tipo), add constraint FKmetodo98695 foreign key (id_tipo) references tipo_dato (id_tipo);
alter table parametro add index FKparametro667407 (id_tipo_dato), add constraint FKparametro667407 foreign key (id_tipo_dato) references tipo_dato (id_tipo);
alter table clase add index FKclase632098 (id_clase), add constraint FKclase632098 foreign key (id_clase) references tipo_dato (id_tipo);
alter table excepcion add index FKexcepcion202527 (id_tipo), add constraint FKexcepcion202527 foreign key (id_tipo) references tipo_dato (id_tipo);
alter table relacion add index FKrelacion696052 (id_diagrama), add constraint FKrelacion696052 foreign key (id_diagrama) references diagrama (id_diagrama);
alter table relacion add index FKrelacion451050 (id_diagrama, id_origen), add constraint FKrelacion451050 foreign key (id_diagrama, id_origen) references clase (id_diagrama, id_clase);
alter table relacion add index FKrelacion797910 (id_diagrama, id_destino), add constraint FKrelacion797910 foreign key (id_diagrama, id_destino) references clase (id_diagrama, id_clase);
alter table atributo add index FKatributo288902 (id_clase), add constraint FKatributo288902 foreign key (id_clase) references clase (id_clase);
alter table metodo add index FKmetodo690174 (id_clase), add constraint FKmetodo690174 foreign key (id_clase) references clase (id_clase);
alter table parametro add index FKparametro693659 (id_clase, id_metodo), add constraint FKparametro693659 foreign key (id_clase, id_metodo) references metodo (id_clase, id_metodo);
alter table excepcion add index FKexcepcion935704 (id_clase, id_metodo), add constraint FKexcepcion935704 foreign key (id_clase, id_metodo) references metodo (id_clase, id_metodo);
